### ISSUE TITLE
Question about "Webpack aliases with Sanity"

### ISSUE THREAD

**Issue by dios-david** [KittyGiraudel/site#112]
Hey, I was reading your post about [Webpack aliases with Sanity](https://github.com/KittyGiraudel/site/blob/main/_posts/2022-05-20-webpack-aliases-with-sanity.md), which is really helpful!

But I ran into an issue which I think would be useful to add to that post. If you use the Sanity GraphQL API, you need to deploy that separately from the Studio. You do that by using the Sanity CLI (e.g. `npx sanity graphql deploy`), which does NOT use webpack, so it will fail as it's unable to resolve the aliases defined in the webpack config.

It's quite annoying, have you run into the same issue?

**Comment by KittyGiraudel** [comment]
Hello David! Thank you for reading that post—I’m glad you liked it. I do not use the GraphQL API so I’m not overly familiar with it, but I can see why that would be a problem. Not too sure how to solve it, besides using [module-alias](https://www.npmjs.com/package/module-alias) to patch the resolution mechanism.
