### ISSUE TITLE
Issue with your RSS feed

### ISSUE THREAD

**Issue by marienfressinaud** [KittyGiraudel/site#55]
Hi Kitty! I noticed an issue with your RSS feed: the HTML tags in your articles are not correctly encoded and are badly displayed. I noticed you simply [replace `<` and `>` by `&lt;` and `&gt;`](https://github.com/KittyGiraudel/site/blob/main/pages/rss/index.liquid#L17). It means the tags that are supposed to be displayed in your article (e.g; `&lt;aside&gt;`) cannot be distinguished from "real" tags by the aggregators. For instance, your article “[Accessible footnotes and a bit of React](https://kittygiraudel.com/2020/11/24/accessible-footnotes-and-a-bit-of-react/)” is really hard to read and can even break the layout of aggregators. Here’s how it looks for me:

![Capture d’écran de 2021-03-08 15-35-31](https://user-images.githubusercontent.com/1436309/110336095-d2dfea80-8024-11eb-86b4-a5f71a18aeb7.png)

I suggest you to not replace `<` and `>`, but to render the RSS `description` tag with a CDATA section:

```
<description><![CDATA[{{ post.templateContent | replace: 'href="/', 'href="https://kittygiraudel.com/' | replace: 'src="/', 'src="https://kittygiraudel.com/' }}]]></description>
```

More information here: https://www.rssboard.org/rss-profile#element-channel-item-description

I think it should be enough :)

**Comment by KittyGiraudel** [comment]
Hello! Thank you so much for reporting it. I’ve just issued a build with your fix: https://github.com/KittyGiraudel/site/commit/8c120227094aa36c05ed962f08752c8e2c44e555. Do you mind checking that it’s fixed please? :)

**Comment by marienfressinaud** [comment]
A lot better!

For some reasons, the indentation of tags is incorrect in your feed (only one space), but I also just noticed that I have an issue in my own aggregator theme (which explains the small margin of the first line).

![Capture d’écran de 2021-03-08 16-06-42](https://user-images.githubusercontent.com/1436309/110339297-4df6d000-8028-11eb-9a38-57a015ed76e6.png)

**Comment by KittyGiraudel** [comment]
Aww, I’m so glad it’s fixed. I didn’t know about this solution, thank you so much. 💖

**Comment by marienfressinaud** [comment]
Glad I could help!
